services:
 backend:
    build: .
    port:
      - "9000:9000"
  db:
    image: MySQL:latest
    environment:
      MYSQL_USER : root
      MYSQL_PASSWORD : PASS
      MYSQL_DB : HOTEL

volumes:
  MYSQL_data: