services:
  db:
    image: mysql:8.0
    container_name: basehotel
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_ROOT_USER}        # MUST NOT be "root"
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      # Allow phpMyAdmin to login as root with the root password from .env
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appH
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env
    ports:
      - "${STREAMLIT_SERVER_PORT:-8501}:8501"
    volumes:
      - /home/aira/Projects/TP/Base/Final_Project/app
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT:-3306}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}

volumes:
  dbdata: